#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "main" ]; then
    printf "\e[31m%s\n\e[m" "[Error]"
    echo "mainブランチは保護されています"
    echo "featureブランチで作業した後、mainブランチへmergeしてください"
    exit 1
fi

npx lint-staged
